# Path
root.directory = /www

# HTTP Settings #
http.port = 8080

# HTTPS Settings #
https.disabled = true
https.port = 8443
https.certificate.path = jhttp.p12
https.certificate.password = 123456

# Modules
modules =
